### ISSUE TITLE
Beta Development Setup Error when installing on MacOS X

### ISSUE THREAD

**Issue by fellipeh** [frappe/bench#237]
Here is the log:

```
SUDO password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [install prequisites] *****************************************************
ok: [localhost] => (item=cmake)
ok: [localhost] => (item=redis)
ok: [localhost] => (item=mariadb)
ok: [localhost] => (item=nodejs)

TASK [cask installs] ***********************************************************
ok: [localhost] => (item=wkhtmltopdf)

TASK [include] *****************************************************************
included: /usr/local/frappe/bench-repo/playbooks/develop/includes/setup_mariadb.yml for localhost

TASK [Install MySQLdb in global env] *******************************************
ok: [localhost]

TASK [Set root Password for Ubuntu] ********************************************
skipping: [localhost] => (item=localhost)
skipping: [localhost] => (item=127.0.0.1)
skipping: [localhost] => (item=::1)

TASK [Add configuration] *******************************************************
ok: [localhost]

TASK [restart mysql linux] *****************************************************
skipping: [localhost]

TASK [add launchagents folder mac] *********************************************
ok: [localhost]

TASK [add mysql to mac startup] ************************************************
ok: [localhost]

TASK [stop mysql mac] **********************************************************
changed: [localhost]

TASK [start mysql mac] *********************************************************
changed: [localhost]

TASK [include] *****************************************************************
included: /usr/local/frappe/bench-repo/playbooks/develop/includes/setup_bench.yml for localhost

TASK [Check if /tmp/.bench exists] *********************************************
ok: [localhost]

TASK [Check if bench_repo_path exists] *****************************************
ok: [localhost]

TASK [move /tmp/.bench if it exists] *******************************************
skipping: [localhost]

TASK [install bench] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/pip install -e /Users/fellipeh/.bench", "failed": true, "msg": "\n:stderr: /Users/fellipeh/.bench should either be a path to a local project or a VCS url beginning with svn+, git+, hg+, or bzr+\nYou are using pip version 8.0.2, however version 8.1.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n"}
	to retry, use: --limit @develop/install.retry

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=2    unreachable=0    failed=1

Traceback (most recent call last):
  File "install.py", line 153, in <module>
    install_bench(args)
  File "install.py", line 58, in install_bench
    run_playbook('develop/install.yml', sudo=True)
  File "install.py", line 131, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(bench_repo, 'playbooks'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'develop/install.yml', '-K']' returned non-zero exit status 2
```

Any idea?

**Comment by anandpdoshi** [comment]
@vjFaLk / @shreyasp can you look into this?

**Comment by shreyasp** [comment]
@fellipeh Can you try re-running the script after doing following steps,
- `rm -rf \tmp\.bench`
- `rm -rf ~\.bench`

**Comment by fellipeh** [comment]
@shreyasp 
I tried that before post.... same error...

I think, the problem can be these:

I have python2 and python3 in  my machine... there's possible the script using python3 instead python2 ?

**Comment by fellipeh** [comment]
Yeah! I think the problem is that script is using python3.. here is the new error:

```
$ python install.py --develop
Password:
The directory '/Users/fellipeh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/fellipeh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): ansible in /usr/local/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python3.5/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python3.5/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python3.5/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python3.5/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python3.5/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/local/lib/python3.5/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python3.5/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python3.5/site-packages (from jinja2->ansible)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python3.5/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python3.5/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible)
SUDO password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Unexpected Exception: name 'urllib2' is not defined
to see the full traceback, use -vvv
Traceback (most recent call last):
  File "install.py", line 153, in <module>
    install_bench(args)
  File "install.py", line 58, in install_bench
    run_playbook('develop/install.yml', sudo=True)
  File "install.py", line 131, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(bench_repo, 'playbooks'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'develop/install.yml', '-K']' returned non-zero exit status 250
```

**Comment by fellipeh** [comment]
Any news about the bug?

**Comment by fellipeh** [comment]
Continue with these error.. I uninstall (brew remove) my python2 and python3... clean up all (`brew cleanup -s` and `rm -rf \tmp\.bench`  `rm -rf ~\.bench` .... ... and install *only* python2.7.... after that, I try again to install...

New error:

```
$ python install.py --develop
The directory '/Users/fellipeh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/fellipeh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): ansible in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/site-packages (from jinja2->ansible)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible)
Traceback (most recent call last):
  File "install.py", line 153, in <module>
    install_bench(args)
  File "install.py", line 58, in install_bench
    run_playbook('develop/install.yml', sudo=True)
  File "install.py", line 131, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(bench_repo, 'playbooks'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by yashodhank** [comment]
Do you have Ansible installed?

**Comment by shreyasp** [comment]
@fellipeh Looking at the error it seems your python is trying to access libraries in brew directory, instead of standard location which is as follows,
`/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7`

you might also have to run, `brew unlink python`

Following is python environment,
- *Python Path* `/usr/bin/python`
- *Python Version* `Python 2.7.10`

**Comment by fellipeh** [comment]
Yeah.. but I run the new python 2.7 installed using HomeBrew... 

it's necessary to use the "macos default" python? I ask that because, it's not a  good approach to use MacOS default python to install and/or update some python packages... makes OS unstable... that's the reason why I use HomeBrew version..

**Comment by shreyasp** [comment]
@fellipeh  Could you please verify whether **subprocess.py** exists in the given location `/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/`

**Comment by fellipeh** [comment]
There`s now /tmp/.bench directory...

```
$ python install.py --develop
Password:
The directory '/Users/fellipeh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/fellipeh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied (use --upgrade to upgrade): ansible in /usr/local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): paramiko in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): PyYAML in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pycrypto>=2.6 in /usr/local/lib/python2.7/site-packages (from ansible)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.1 in /usr/local/lib/python2.7/site-packages (from paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python2.7/site-packages (from jinja2->ansible)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.1->paramiko->ansible)
Requirement already satisfied (use --upgrade to upgrade): pycparser in /usr/local/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible)
Traceback (most recent call last):
  File "install.py", line 153, in <module>
    install_bench(args)
  File "install.py", line 58, in install_bench
    run_playbook('develop/install.yml', sudo=True)
  File "install.py", line 131, in run_playbook
    success = subprocess.check_call(args, cwd=os.path.join(bench_repo, 'playbooks'))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
```
fellipeh@skynet:~$ ls /tmp/.bench
ls: /tmp/.bench: No such file or directory

```

**Comment by JAGwar1905** [comment]
python install.py --develop

I am getting the same error on Ubuntu 14.04
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available

python3 --version
Python 3.4.2
which python
/usr/bin/python
/usr/bin/python --version
Python 2.7.9

Any help please?

**Comment by anandpdoshi** [comment]
I think this problem is due to the installer fetching code from master branch. I've updated the readme.

Run this:

```
curl "https://raw.githubusercontent.com/frappe/bench/develop/playbooks/install.py" -o install.py

# for development
sudo python install.py --develop
```

**Comment by safo-bora** [comment]
Hello guys! 

After:
> sudo python install.py --develop --user frappe

New user 'frappe' was created (but I don’t know password and can’t login with it. )

But the main  problem is:
My general account is fully broken. I have "Permission denied" for all user folders.
I was really surprised that  frappe installation did something wrong with my OS.

> MacBook:~ work$ brew cask install iterm2
> ==> Tapping caskroom/cask
> fatal: could not create leading directories of '/usr/local/Library/Taps/caskroom/homebrew-cask': Permission denied

**Comment by yashodhank** [comment]
@safo-bora enter following to switch to root shell on your mac
```
$ sudo su
```
Then, create a new user / fix permissions etc.
or try: https://www.maketecheasier.com/enable-root-user-mac/

**Comment by rmehta** [comment]
@safo-bora delete the user and install without `--user frappe`

If you have an issue, start a new thread. Closing this one.

**Comment by dawoodjee** [comment]
Any solution to this issue. @rmehta the problem is still there. Tried all suggestions here, including Ubuntu 14 and 16 OSs.
